import type { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialDatabase1770336830026 implements MigrationInterface {
    name = 'InitialDatabase1770336830026'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."language_code_enum" AS ENUM('pl', 'en')`);
        await queryRunner.query(`CREATE TABLE "language" ("id" SERIAL NOT NULL, "code" "public"."language_code_enum" NOT NULL, "name" character varying(100) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_465b3173cdddf0ac2d3fe73a33c" UNIQUE ("code"), CONSTRAINT "PK_cc0a99e710eb3733f6fb42b1d4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_translation" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "date_creation" TIMESTAMP NOT NULL, "date_modification" TIMESTAMP, "language_id" integer, "role_id" integer, CONSTRAINT "PK_d77adbb77a00100d675f72481a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."role_code_enum" AS ENUM('user', 'manager', 'admin')`);
        await queryRunner.query(`CREATE TABLE "role" ("id" SERIAL NOT NULL, "code" "public"."role_code_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "date_creation" TIMESTAMP NOT NULL, "date_modification" TIMESTAMP, CONSTRAINT "UQ_ee999bb389d7ac0fd967172c41f" UNIQUE ("code"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_token" ("id" SERIAL NOT NULL, "token" character varying NOT NULL, "date_expiration" TIMESTAMP NOT NULL, "user_id" integer, CONSTRAINT "PK_b575dd3c21fb0831013c909e7fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c31d0a2f38e6e99110df62ab0a" ON "refresh_token" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_14386e3c0d0a6281df77e1e2e7" ON "refresh_token" ("date_expiration") `);
        await queryRunner.query(`CREATE INDEX "IDX_6bbe63d2fe75e7f0ba1710351d" ON "refresh_token" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."file_storage_type_enum" AS ENUM('local')`);
        await queryRunner.query(`CREATE TABLE "file" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filename" text NOT NULL, "original_name" text NOT NULL, "path" text NOT NULL, "mimetype" text NOT NULL, "encoding" text NOT NULL, "size" bigint NOT NULL, "storage_type" "public"."file_storage_type_enum" NOT NULL, "url" text, "metadata" jsonb, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP NOT NULL DEFAULT now(), "date_deletion" TIMESTAMP, CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_role_permission_translation" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, "project_role_permission_id" integer, "language_id" integer, CONSTRAINT "PK_2de3b21001ec341a406bd5d2e4b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_role_permission_code_enum" AS ENUM('EDIT_PROJECT', 'DELETE_PROJECT', 'SHOW_TASKS', 'INVITE_USERS', 'MANAGE_MEMBERS', 'VIEW_PROJECT', 'MANAGE_TASKS')`);
        await queryRunner.query(`CREATE TABLE "project_role_permission" ("id" SERIAL NOT NULL, "code" "public"."project_role_permission_code_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, CONSTRAINT "UQ_83025270eca71938284399bcc8e" UNIQUE ("code"), CONSTRAINT "PK_f7b00ca3d08ec1730ea8184c3c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_role_translation" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, "project_role_id" integer, "language_id" integer, CONSTRAINT "PK_213d7be069683929b9de0b479be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_role_code_enum" AS ENUM('manager', 'client', 'member')`);
        await queryRunner.query(`CREATE TABLE "project_role" ("id" SERIAL NOT NULL, "code" "public"."project_role_code_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, CONSTRAINT "UQ_b0bdf5142650e33f03bbca6a01b" UNIQUE ("code"), CONSTRAINT "PK_5974798305ac81d4a7d23ab1c6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_category_translation" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "language_id" integer, "project_category_id" integer, CONSTRAINT "PK_95f7eaf60eb4227e0ce2337d090" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_category" ("id" SERIAL NOT NULL, "color" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "project_id" integer, CONSTRAINT "PK_826c5e0f45e35b5983c8379be7b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_status_translation" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "language_id" integer, "project_status_id" integer, CONSTRAINT "PK_1b416979d4a6eda0a093fa8fe77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_status" ("id" SERIAL NOT NULL, "color" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "project_id" integer, CONSTRAINT "PK_625ed5469429a6b32e34ba9f827" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_attachment" ("id" SERIAL NOT NULL, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP NOT NULL DEFAULT now(), "task_id" integer, "file_id" uuid, CONSTRAINT "PK_b9dd4c7184d6c02636decffa219" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_comment_attachment" ("id" SERIAL NOT NULL, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP NOT NULL DEFAULT now(), "comment_id" integer, "file_id" uuid, CONSTRAINT "PK_73bef66b827f3c41cfaced57d37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_comment" ("id" SERIAL NOT NULL, "content" text NOT NULL, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, "task_id" integer, "author_id" integer, CONSTRAINT "PK_28da4411b195bfc3c451cfa21ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_priority_translation" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, "language_id" integer, "priority_id" integer, CONSTRAINT "PK_af814d3c5cede7dfa6c53ecc21f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."task_priority_code_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TABLE "task_priority" ("id" SERIAL NOT NULL, "code" "public"."task_priority_code_enum" NOT NULL, "color" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, CONSTRAINT "PK_42fc82c4e184b727a3ccd7863ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task" ("id" SERIAL NOT NULL, "description" text NOT NULL, "additional_description" text, "price_estimation" integer NOT NULL DEFAULT '0', "worked_time" integer NOT NULL DEFAULT '0', "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, "access_role_id" integer, "project_id" integer, "created_by_id" integer, "priority_id" integer, "status_id" integer, CONSTRAINT "PK_fb213f79ee45060ba925ecd576e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_type_translation" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "language_id" integer, "project_type_id" integer, CONSTRAINT "PK_e7cd7fdc326c40db0d556837664" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_type_code_enum" AS ENUM('tickets', 'backlog')`);
        await queryRunner.query(`CREATE TABLE "project_type" ("id" SERIAL NOT NULL, "code" "public"."project_type_code_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_a2a57a982e469ae425150b858a0" UNIQUE ("code"), CONSTRAINT "PK_2a06e25261f5e8eb431d3683931" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "is_public" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, "icon_id" uuid, "type_id" integer, CONSTRAINT "PK_4d68b1358bb5b766d3e78f32f57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_user_role" ("id" SERIAL NOT NULL, "date_assigned" TIMESTAMP NOT NULL DEFAULT now(), "project_id" integer, "user_id" integer, "project_role_id" integer NOT NULL, CONSTRAINT "PK_c152ea4723da75790e2ed26b923" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_email_history" ("id" SERIAL NOT NULL, "old_email" character varying NOT NULL, "new_email" character varying NOT NULL, "date_change" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_1dd2733a2c37820f8a82bf52d1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, "is_email_confirmed" boolean NOT NULL DEFAULT false, "confirmation_token" character varying, "confirmation_token_expiry" TIMESTAMP, "terms_accepted" boolean NOT NULL DEFAULT false, "privacy_policy_accepted" boolean NOT NULL DEFAULT false, "date_terms_acceptance" TIMESTAMP, "date_privacy_policy_acceptance" TIMESTAMP, "email_change_token" character varying, "pending_email" character varying, "email_change_token_expiry" TIMESTAMP, "avatar_id" uuid, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_role" ("id" SERIAL NOT NULL, "user_id" integer, "role_id" integer, CONSTRAINT "PK_fb2e442d14add3cefbdf33c4561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "terms" ("id" SERIAL NOT NULL, "version" character varying NOT NULL, "date_effective" TIMESTAMP NOT NULL, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, CONSTRAINT "PK_33b6fe77d6ace7ff43cc8a65958" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."terms_section_type_enum" AS ENUM('header', 'paragraph', 'list')`);
        await queryRunner.query(`CREATE TABLE "terms_section" ("id" SERIAL NOT NULL, "order" integer NOT NULL, "type" "public"."terms_section_type_enum" NOT NULL, "terms_id" integer, CONSTRAINT "PK_d63f82da0cfeb99de10d02c899c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "terms_section_translation" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "content" text, "items" text, "language_id" integer, "section_id" integer, CONSTRAINT "PK_6d2f0695be0fcbc8791da8c86c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "privacy_policy_section_translation" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "content" text, "items" text, "language_id" integer, "section_id" integer, CONSTRAINT "PK_972047b09a24578e5d589890ae6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "privacy_policy" ("id" SERIAL NOT NULL, "version" character varying NOT NULL, "date_effective" TIMESTAMP NOT NULL, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP, CONSTRAINT "PK_5df3ca7aac1ca728f541a31fa74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."privacy_policy_section_type_enum" AS ENUM('header', 'paragraph', 'list')`);
        await queryRunner.query(`CREATE TABLE "privacy_policy_section" ("id" SERIAL NOT NULL, "order" integer NOT NULL, "type" "public"."privacy_policy_section_type_enum" NOT NULL, "privacy_policy_id" integer, CONSTRAINT "PK_22cc856991a2936a2ed1aef777e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_status_translation" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "language_id" integer, "task_status_id" integer, CONSTRAINT "PK_bef2fdedfde7507460a60cd7b90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_status" ("id" SERIAL NOT NULL, "color" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_b8747cc6a41b6cef4639babf61d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_category_translation" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "language_id" integer, "task_category_id" integer, CONSTRAINT "PK_17c06b53e88f42953aac52fd9f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_category" ("id" SERIAL NOT NULL, "color" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_5a2a57aed53e11558e410ddb44d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_invitation_status_enum" AS ENUM('pending', 'accepted', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "project_invitation" ("id" SERIAL NOT NULL, "status" "public"."project_invitation_status_enum" NOT NULL DEFAULT 'pending', "date_created" TIMESTAMP NOT NULL DEFAULT now(), "date_updated" TIMESTAMP NOT NULL DEFAULT now(), "project_id" integer, "user_id" integer, "inviter_id" integer, "role_id" integer, CONSTRAINT "PK_ba41c49adf5e2c6e828de7a108d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum" AS ENUM('project_invitation', 'task_assigned', 'task_completed', 'project_update', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_status_enum" AS ENUM('unread', 'read')`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" SERIAL NOT NULL, "type" "public"."notification_type_enum" NOT NULL, "status" "public"."notification_status_enum" NOT NULL DEFAULT 'unread', "data" json, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP NOT NULL DEFAULT now(), "recipient_id" integer, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_translation" ("id" SERIAL NOT NULL, "title" character varying(100) NOT NULL, "message" text NOT NULL, "language_id" integer, "notification_id" integer, CONSTRAINT "PK_bad4c1c3e66a739192f94a231c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_settings" ("id" SERIAL NOT NULL, "email_notifications" boolean NOT NULL DEFAULT true, "app_notifications" boolean NOT NULL DEFAULT true, "project_invitations" boolean NOT NULL DEFAULT true, "task_assignments" boolean NOT NULL DEFAULT true, "task_comments" boolean NOT NULL DEFAULT true, "task_status_changes" boolean NOT NULL DEFAULT true, "project_updates" boolean NOT NULL DEFAULT true, "system_notifications" boolean NOT NULL DEFAULT true, "date_creation" TIMESTAMP NOT NULL DEFAULT now(), "date_modification" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_d131abd7996c475ef768d4559ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_role_to_permission" ("project_role_permission_id" integer NOT NULL, "project_role_id" integer NOT NULL, CONSTRAINT "PK_4562f5bc23697ddcaf0296c5dff" PRIMARY KEY ("project_role_permission_id", "project_role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2de0d445d04daac43217786487" ON "project_role_to_permission" ("project_role_permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f2c7d09e90ff5c86c75471b54" ON "project_role_to_permission" ("project_role_id") `);
        await queryRunner.query(`CREATE TABLE "task_assigned_user" ("task_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_b653b5d5675af225e88fc52409c" PRIMARY KEY ("task_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8499579dab22030edbcd652503" ON "task_assigned_user" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5797b45c7c0b661ee43b5136e" ON "task_assigned_user" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "task_category" DROP CONSTRAINT "PK_5a2a57aed53e11558e410ddb44d"`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD CONSTRAINT "PK_5a2a57aed53e11558e410ddb44d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD "color" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD "task_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP CONSTRAINT "PK_5a2a57aed53e11558e410ddb44d"`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD CONSTRAINT "PK_c74db562070796f6fcdda5cbcf5" PRIMARY KEY ("id", "task_id")`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD "category_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP CONSTRAINT "PK_c74db562070796f6fcdda5cbcf5"`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD CONSTRAINT "PK_d9862de51104d0eef79587e5fed" PRIMARY KEY ("id", "task_id", "category_id")`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP CONSTRAINT "PK_d9862de51104d0eef79587e5fed"`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD CONSTRAINT "PK_2c87cf4bfb2bbe96a89093a7537" PRIMARY KEY ("task_id", "category_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_f9bef39c540fc7a79b626663bb" ON "task_category" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b9f70ffaddf3102ab6bc072e9" ON "task_category" ("category_id") `);
        await queryRunner.query(`ALTER TABLE "role_translation" ADD CONSTRAINT "FK_c3c4604a7bdfc79676f92556468" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_translation" ADD CONSTRAINT "FK_41a13cf6a248d9d0413cc5b71f2" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_token" ADD CONSTRAINT "FK_6bbe63d2fe75e7f0ba1710351d4" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_permission_translation" ADD CONSTRAINT "FK_8242433736588d55ba563d3a16a" FOREIGN KEY ("project_role_permission_id") REFERENCES "project_role_permission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_permission_translation" ADD CONSTRAINT "FK_583e198d2f1122e52eb952b6a72" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_translation" ADD CONSTRAINT "FK_a70c62fa126ebcb7882d8ad978b" FOREIGN KEY ("project_role_id") REFERENCES "project_role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_translation" ADD CONSTRAINT "FK_9f1b297ce67de0aaae4a496ab4e" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_category_translation" ADD CONSTRAINT "FK_590476214666d0de2751e13f658" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_category_translation" ADD CONSTRAINT "FK_c3e7431d3bca382968efaa8225d" FOREIGN KEY ("project_category_id") REFERENCES "project_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_category" ADD CONSTRAINT "FK_99d66734488559ed1c616e737c7" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_status_translation" ADD CONSTRAINT "FK_19ea74e576f7f306fccc97cfc9b" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_status_translation" ADD CONSTRAINT "FK_40d3a5b25087bb5abf80ffd1eba" FOREIGN KEY ("project_status_id") REFERENCES "project_status"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_status" ADD CONSTRAINT "FK_0236d730cfc98f39538a122d340" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_attachment" ADD CONSTRAINT "FK_81bb33ae540bb0e3fc7fc4f9669" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_attachment" ADD CONSTRAINT "FK_d10041828e9ef899658aed70d71" FOREIGN KEY ("file_id") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comment_attachment" ADD CONSTRAINT "FK_7c222df0839491db56a377396ff" FOREIGN KEY ("comment_id") REFERENCES "task_comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comment_attachment" ADD CONSTRAINT "FK_729a55883b45ed92017374ebce0" FOREIGN KEY ("file_id") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comment" ADD CONSTRAINT "FK_55866536e2125e25624db4d963b" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comment" ADD CONSTRAINT "FK_cdb2dcdeb59c097579beb53cb33" FOREIGN KEY ("author_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_priority_translation" ADD CONSTRAINT "FK_a854da1826c3fe39f7e06db1c6c" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_priority_translation" ADD CONSTRAINT "FK_1b13414aa4e192b1b5767ae073e" FOREIGN KEY ("priority_id") REFERENCES "task_priority"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_167ba7c79e8b096b05d92d49687" FOREIGN KEY ("access_role_id") REFERENCES "project_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_1f53e7ffe94530f9e0221224d29" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_8c02c2c774eff4192dd44533db3" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_42fc82c4e184b727a3ccd7863ee" FOREIGN KEY ("priority_id") REFERENCES "task_priority"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_b8747cc6a41b6cef4639babf61d" FOREIGN KEY ("status_id") REFERENCES "project_status"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_type_translation" ADD CONSTRAINT "FK_19ae66a528c45eb6a0b09016056" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_type_translation" ADD CONSTRAINT "FK_0998429b7c4b3d03989ef400834" FOREIGN KEY ("project_type_id") REFERENCES "project_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_2f9a21f0c7a0b88238fff8ea6ed" FOREIGN KEY ("icon_id") REFERENCES "file"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_2a06e25261f5e8eb431d3683931" FOREIGN KEY ("type_id") REFERENCES "project_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_user_role" ADD CONSTRAINT "FK_8c2e74b71ada839c59dbc133599" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_user_role" ADD CONSTRAINT "FK_37ff8801e5eec3c06ce7f202a5e" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_user_role" ADD CONSTRAINT "FK_26abda0f8f9f62dacc8a19271ec" FOREIGN KEY ("project_role_id") REFERENCES "project_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_email_history" ADD CONSTRAINT "FK_3d39b06063fd77c460ca7e80c13" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_b777e56620c3f1ac0308514fc4c" FOREIGN KEY ("avatar_id") REFERENCES "file"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terms_section" ADD CONSTRAINT "FK_948eace940c2e121f81572f7ada" FOREIGN KEY ("terms_id") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terms_section_translation" ADD CONSTRAINT "FK_5a38268383945ff785e3babf520" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terms_section_translation" ADD CONSTRAINT "FK_1731d07af48b43eee9145772683" FOREIGN KEY ("section_id") REFERENCES "terms_section"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "privacy_policy_section_translation" ADD CONSTRAINT "FK_cce39f32723f26779a3dfd33c61" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "privacy_policy_section_translation" ADD CONSTRAINT "FK_5f4898ac42961422b4492020333" FOREIGN KEY ("section_id") REFERENCES "privacy_policy_section"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "privacy_policy_section" ADD CONSTRAINT "FK_ad5e4bad705c963211ab00e2772" FOREIGN KEY ("privacy_policy_id") REFERENCES "privacy_policy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_status_translation" ADD CONSTRAINT "FK_3df13126bdf9fe8f353d005d336" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_status_translation" ADD CONSTRAINT "FK_4f5800db2ac5c03f274bb613f71" FOREIGN KEY ("task_status_id") REFERENCES "task_status"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_category_translation" ADD CONSTRAINT "FK_3b2c75ecf0a76f08f0a1176c071" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_category_translation" ADD CONSTRAINT "FK_85d07a5bb361f6edbf16d677afc" FOREIGN KEY ("task_category_id") REFERENCES "task_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_invitation" ADD CONSTRAINT "FK_9dd317f479606b1165e963a24a0" FOREIGN KEY ("project_id") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_invitation" ADD CONSTRAINT "FK_11b44981c4b5277ce9f4e113d59" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_invitation" ADD CONSTRAINT "FK_8b78789d41f5d2efbc66c730049" FOREIGN KEY ("inviter_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_invitation" ADD CONSTRAINT "FK_5914434c129ef6d82eecd00dd81" FOREIGN KEY ("role_id") REFERENCES "project_role"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_9830357f52360a126737d498e66" FOREIGN KEY ("recipient_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_translation" ADD CONSTRAINT "FK_d1238543d00b7a5be510a209491" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_translation" ADD CONSTRAINT "FK_b9242e7e73362d6a92d8f62052d" FOREIGN KEY ("notification_id") REFERENCES "notification"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ADD CONSTRAINT "FK_91a7ffebe8b406c4470845d4781" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_to_permission" ADD CONSTRAINT "FK_2de0d445d04daac43217786487a" FOREIGN KEY ("project_role_permission_id") REFERENCES "project_role_permission"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_role_to_permission" ADD CONSTRAINT "FK_4f2c7d09e90ff5c86c75471b547" FOREIGN KEY ("project_role_id") REFERENCES "project_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_assigned_user" ADD CONSTRAINT "FK_8499579dab22030edbcd652503b" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_assigned_user" ADD CONSTRAINT "FK_d5797b45c7c0b661ee43b5136e9" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD CONSTRAINT "FK_f9bef39c540fc7a79b626663bb1" FOREIGN KEY ("task_id") REFERENCES "task"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD CONSTRAINT "FK_2b9f70ffaddf3102ab6bc072e9e" FOREIGN KEY ("category_id") REFERENCES "project_category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_category" DROP CONSTRAINT "FK_2b9f70ffaddf3102ab6bc072e9e"`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP CONSTRAINT "FK_f9bef39c540fc7a79b626663bb1"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_user" DROP CONSTRAINT "FK_d5797b45c7c0b661ee43b5136e9"`);
        await queryRunner.query(`ALTER TABLE "task_assigned_user" DROP CONSTRAINT "FK_8499579dab22030edbcd652503b"`);
        await queryRunner.query(`ALTER TABLE "project_role_to_permission" DROP CONSTRAINT "FK_4f2c7d09e90ff5c86c75471b547"`);
        await queryRunner.query(`ALTER TABLE "project_role_to_permission" DROP CONSTRAINT "FK_2de0d445d04daac43217786487a"`);
        await queryRunner.query(`ALTER TABLE "notification_settings" DROP CONSTRAINT "FK_91a7ffebe8b406c4470845d4781"`);
        await queryRunner.query(`ALTER TABLE "notification_translation" DROP CONSTRAINT "FK_b9242e7e73362d6a92d8f62052d"`);
        await queryRunner.query(`ALTER TABLE "notification_translation" DROP CONSTRAINT "FK_d1238543d00b7a5be510a209491"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_9830357f52360a126737d498e66"`);
        await queryRunner.query(`ALTER TABLE "project_invitation" DROP CONSTRAINT "FK_5914434c129ef6d82eecd00dd81"`);
        await queryRunner.query(`ALTER TABLE "project_invitation" DROP CONSTRAINT "FK_8b78789d41f5d2efbc66c730049"`);
        await queryRunner.query(`ALTER TABLE "project_invitation" DROP CONSTRAINT "FK_11b44981c4b5277ce9f4e113d59"`);
        await queryRunner.query(`ALTER TABLE "project_invitation" DROP CONSTRAINT "FK_9dd317f479606b1165e963a24a0"`);
        await queryRunner.query(`ALTER TABLE "task_category_translation" DROP CONSTRAINT "FK_85d07a5bb361f6edbf16d677afc"`);
        await queryRunner.query(`ALTER TABLE "task_category_translation" DROP CONSTRAINT "FK_3b2c75ecf0a76f08f0a1176c071"`);
        await queryRunner.query(`ALTER TABLE "task_status_translation" DROP CONSTRAINT "FK_4f5800db2ac5c03f274bb613f71"`);
        await queryRunner.query(`ALTER TABLE "task_status_translation" DROP CONSTRAINT "FK_3df13126bdf9fe8f353d005d336"`);
        await queryRunner.query(`ALTER TABLE "privacy_policy_section" DROP CONSTRAINT "FK_ad5e4bad705c963211ab00e2772"`);
        await queryRunner.query(`ALTER TABLE "privacy_policy_section_translation" DROP CONSTRAINT "FK_5f4898ac42961422b4492020333"`);
        await queryRunner.query(`ALTER TABLE "privacy_policy_section_translation" DROP CONSTRAINT "FK_cce39f32723f26779a3dfd33c61"`);
        await queryRunner.query(`ALTER TABLE "terms_section_translation" DROP CONSTRAINT "FK_1731d07af48b43eee9145772683"`);
        await queryRunner.query(`ALTER TABLE "terms_section_translation" DROP CONSTRAINT "FK_5a38268383945ff785e3babf520"`);
        await queryRunner.query(`ALTER TABLE "terms_section" DROP CONSTRAINT "FK_948eace940c2e121f81572f7ada"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_b777e56620c3f1ac0308514fc4c"`);
        await queryRunner.query(`ALTER TABLE "user_email_history" DROP CONSTRAINT "FK_3d39b06063fd77c460ca7e80c13"`);
        await queryRunner.query(`ALTER TABLE "project_user_role" DROP CONSTRAINT "FK_26abda0f8f9f62dacc8a19271ec"`);
        await queryRunner.query(`ALTER TABLE "project_user_role" DROP CONSTRAINT "FK_37ff8801e5eec3c06ce7f202a5e"`);
        await queryRunner.query(`ALTER TABLE "project_user_role" DROP CONSTRAINT "FK_8c2e74b71ada839c59dbc133599"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_2a06e25261f5e8eb431d3683931"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_2f9a21f0c7a0b88238fff8ea6ed"`);
        await queryRunner.query(`ALTER TABLE "project_type_translation" DROP CONSTRAINT "FK_0998429b7c4b3d03989ef400834"`);
        await queryRunner.query(`ALTER TABLE "project_type_translation" DROP CONSTRAINT "FK_19ae66a528c45eb6a0b09016056"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_b8747cc6a41b6cef4639babf61d"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_42fc82c4e184b727a3ccd7863ee"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_8c02c2c774eff4192dd44533db3"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_1f53e7ffe94530f9e0221224d29"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_167ba7c79e8b096b05d92d49687"`);
        await queryRunner.query(`ALTER TABLE "task_priority_translation" DROP CONSTRAINT "FK_1b13414aa4e192b1b5767ae073e"`);
        await queryRunner.query(`ALTER TABLE "task_priority_translation" DROP CONSTRAINT "FK_a854da1826c3fe39f7e06db1c6c"`);
        await queryRunner.query(`ALTER TABLE "task_comment" DROP CONSTRAINT "FK_cdb2dcdeb59c097579beb53cb33"`);
        await queryRunner.query(`ALTER TABLE "task_comment" DROP CONSTRAINT "FK_55866536e2125e25624db4d963b"`);
        await queryRunner.query(`ALTER TABLE "task_comment_attachment" DROP CONSTRAINT "FK_729a55883b45ed92017374ebce0"`);
        await queryRunner.query(`ALTER TABLE "task_comment_attachment" DROP CONSTRAINT "FK_7c222df0839491db56a377396ff"`);
        await queryRunner.query(`ALTER TABLE "task_attachment" DROP CONSTRAINT "FK_d10041828e9ef899658aed70d71"`);
        await queryRunner.query(`ALTER TABLE "task_attachment" DROP CONSTRAINT "FK_81bb33ae540bb0e3fc7fc4f9669"`);
        await queryRunner.query(`ALTER TABLE "project_status" DROP CONSTRAINT "FK_0236d730cfc98f39538a122d340"`);
        await queryRunner.query(`ALTER TABLE "project_status_translation" DROP CONSTRAINT "FK_40d3a5b25087bb5abf80ffd1eba"`);
        await queryRunner.query(`ALTER TABLE "project_status_translation" DROP CONSTRAINT "FK_19ea74e576f7f306fccc97cfc9b"`);
        await queryRunner.query(`ALTER TABLE "project_category" DROP CONSTRAINT "FK_99d66734488559ed1c616e737c7"`);
        await queryRunner.query(`ALTER TABLE "project_category_translation" DROP CONSTRAINT "FK_c3e7431d3bca382968efaa8225d"`);
        await queryRunner.query(`ALTER TABLE "project_category_translation" DROP CONSTRAINT "FK_590476214666d0de2751e13f658"`);
        await queryRunner.query(`ALTER TABLE "project_role_translation" DROP CONSTRAINT "FK_9f1b297ce67de0aaae4a496ab4e"`);
        await queryRunner.query(`ALTER TABLE "project_role_translation" DROP CONSTRAINT "FK_a70c62fa126ebcb7882d8ad978b"`);
        await queryRunner.query(`ALTER TABLE "project_role_permission_translation" DROP CONSTRAINT "FK_583e198d2f1122e52eb952b6a72"`);
        await queryRunner.query(`ALTER TABLE "project_role_permission_translation" DROP CONSTRAINT "FK_8242433736588d55ba563d3a16a"`);
        await queryRunner.query(`ALTER TABLE "refresh_token" DROP CONSTRAINT "FK_6bbe63d2fe75e7f0ba1710351d4"`);
        await queryRunner.query(`ALTER TABLE "role_translation" DROP CONSTRAINT "FK_41a13cf6a248d9d0413cc5b71f2"`);
        await queryRunner.query(`ALTER TABLE "role_translation" DROP CONSTRAINT "FK_c3c4604a7bdfc79676f92556468"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b9f70ffaddf3102ab6bc072e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9bef39c540fc7a79b626663bb"`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP CONSTRAINT "PK_2c87cf4bfb2bbe96a89093a7537"`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD CONSTRAINT "PK_d9862de51104d0eef79587e5fed" PRIMARY KEY ("id", "task_id", "category_id")`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP CONSTRAINT "PK_d9862de51104d0eef79587e5fed"`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD CONSTRAINT "PK_c74db562070796f6fcdda5cbcf5" PRIMARY KEY ("id", "task_id")`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP CONSTRAINT "PK_c74db562070796f6fcdda5cbcf5"`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD CONSTRAINT "PK_5a2a57aed53e11558e410ddb44d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP COLUMN "task_id"`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP CONSTRAINT "PK_5a2a57aed53e11558e410ddb44d"`);
        await queryRunner.query(`ALTER TABLE "task_category" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD "color" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "task_category" ADD CONSTRAINT "PK_5a2a57aed53e11558e410ddb44d" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5797b45c7c0b661ee43b5136e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8499579dab22030edbcd652503"`);
        await queryRunner.query(`DROP TABLE "task_assigned_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f2c7d09e90ff5c86c75471b54"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2de0d445d04daac43217786487"`);
        await queryRunner.query(`DROP TABLE "project_role_to_permission"`);
        await queryRunner.query(`DROP TABLE "notification_settings"`);
        await queryRunner.query(`DROP TABLE "notification_translation"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TYPE "public"."notification_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "project_invitation"`);
        await queryRunner.query(`DROP TYPE "public"."project_invitation_status_enum"`);
        await queryRunner.query(`DROP TABLE "task_category"`);
        await queryRunner.query(`DROP TABLE "task_category_translation"`);
        await queryRunner.query(`DROP TABLE "task_status"`);
        await queryRunner.query(`DROP TABLE "task_status_translation"`);
        await queryRunner.query(`DROP TABLE "privacy_policy_section"`);
        await queryRunner.query(`DROP TYPE "public"."privacy_policy_section_type_enum"`);
        await queryRunner.query(`DROP TABLE "privacy_policy"`);
        await queryRunner.query(`DROP TABLE "privacy_policy_section_translation"`);
        await queryRunner.query(`DROP TABLE "terms_section_translation"`);
        await queryRunner.query(`DROP TABLE "terms_section"`);
        await queryRunner.query(`DROP TYPE "public"."terms_section_type_enum"`);
        await queryRunner.query(`DROP TABLE "terms"`);
        await queryRunner.query(`DROP TABLE "user_role"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "user_email_history"`);
        await queryRunner.query(`DROP TABLE "project_user_role"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`DROP TABLE "project_type"`);
        await queryRunner.query(`DROP TYPE "public"."project_type_code_enum"`);
        await queryRunner.query(`DROP TABLE "project_type_translation"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`DROP TABLE "task_priority"`);
        await queryRunner.query(`DROP TYPE "public"."task_priority_code_enum"`);
        await queryRunner.query(`DROP TABLE "task_priority_translation"`);
        await queryRunner.query(`DROP TABLE "task_comment"`);
        await queryRunner.query(`DROP TABLE "task_comment_attachment"`);
        await queryRunner.query(`DROP TABLE "task_attachment"`);
        await queryRunner.query(`DROP TABLE "project_status"`);
        await queryRunner.query(`DROP TABLE "project_status_translation"`);
        await queryRunner.query(`DROP TABLE "project_category"`);
        await queryRunner.query(`DROP TABLE "project_category_translation"`);
        await queryRunner.query(`DROP TABLE "project_role"`);
        await queryRunner.query(`DROP TYPE "public"."project_role_code_enum"`);
        await queryRunner.query(`DROP TABLE "project_role_translation"`);
        await queryRunner.query(`DROP TABLE "project_role_permission"`);
        await queryRunner.query(`DROP TYPE "public"."project_role_permission_code_enum"`);
        await queryRunner.query(`DROP TABLE "project_role_permission_translation"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP TYPE "public"."file_storage_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bbe63d2fe75e7f0ba1710351d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14386e3c0d0a6281df77e1e2e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c31d0a2f38e6e99110df62ab0a"`);
        await queryRunner.query(`DROP TABLE "refresh_token"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TYPE "public"."role_code_enum"`);
        await queryRunner.query(`DROP TABLE "role_translation"`);
        await queryRunner.query(`DROP TABLE "language"`);
        await queryRunner.query(`DROP TYPE "public"."language_code_enum"`);
    }

}
