export enum NotificationTypeEnum {
  PROJECT_INVITATION = 'PROJECT_INVITATION',
  PROJECT_MEMBER_JOINED = 'PROJECT_MEMBER_JOINED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  TASK_COMMENT_ADDED = 'TASK_COMMENT_ADDED',
}
