export enum ProjectRolePermissionEnum {
  VIEW_PROJECT = 'VIEW_PROJECT',
  EDIT_PROJECT = 'EDIT_PROJECT',
  DELETE_PROJECT = 'DELETE_PROJECT',
  INVITE_USERS = 'INVITE_USERS',
  MANAGE_MEMBERS = 'MANAGE_MEMBERS',
}
